---
github_account: archf
# requirements:

description: |
  Install and configure ntpd on rhel and debian hosts. This is only suitable
  for client-server mode. Target can either be a ntpd server or a ntpd client.

  Settings above work well for simple ntp clients.  See `templates/ntp.conf.j2`
  for other defaults.

todos:
  - peer support?
  - improve statistics configuration

role_stack: |
  This role was carefully selected to be part an ultimate deck of roles to manage
  your infrastructure.

  All roles' documentation is wrapped in this [convenient guide](http://127.0.0.1:8000/).
