---

# user public ssh keys fetching

- name: fetch {{users_default_domain}} public ssh keys back to control machine
  fetch:
    src: "{{item.home|default(users_defaults.home)}}/{{item.name}}/.ssh/{{item.name}}.{{users_default_domain}}.pub"
    dest: "{{groups_dir}}/{{usergroupname}}/keys/"
    flat: yes
  with_items:
    - "{{users}}"
  when: users_default_domain is defined

- name: fetch 'ssh_domains' public ssh keys back to control machine
  fetch:
    src: "{{item.0.home|default(users_defaults.home)}}/{{item.0.name}}/.ssh/{{item.0.name}}.{{item.1}}.pub"
    dest: "{{groups_dir}}/{{usergroupname}}/keys/"
    flat: yes
  with_nested:
    - "{{users}}"
    - ssh_domains
  when: item.1
