---
galaxy_info:
  author: "Felix Archambault"
  description: A role to create and configure user accounts and groups on a host.
  min_ansible_version: 2.1
  license: BSD

  platforms:
   - name: EL
     versions:
      - 5
      - 6
   - name: Fedora
     versions:
      - 16
      - 17
      - 18
   - name: Ubuntu
     versions:
      - precise
      - quantal
      - raring
      - saucy
   - name: SLES
     versions:
      - 11
  galaxy_tags:
   - users
   - accounts
   - ssh_config
   - system
dependencies: []
