---
galaxy_info:
  author: "Felix Archambault"
  description: Install and configure ntpd on a target host.
  min_ansible_version: 1.9
  license: BSD

  platforms:
   - name: EL
     versions:
      - 5
      - 6
   - name: Fedora
     versions:
      - 16
      - 17
      - 18
   - name: Ubuntu
     versions:
      - precise
      - quantal
      - raring
      - saucy
   - name: SLES
     versions:
      - 11
  galaxy_tags:
   - ntp
   - system
dependencies: []
