---
# file: tasks/main.yml

# specify the packages and the packager to use
- name: load OS specific variables (see ../vars/*)
  include_vars: "{{ ansible_os_family }}.yml"

- name: install required ppas on ubuntu machines
  apt_repository: repo="{{ item }}"
  with_items: apt_repos
  when: ansible_distribution == "Ubuntu" and apt_repos is defined

- name: install packages
  package: name={{ workstation_pkgs }} state={{ workstation_pkg_state }}

- name: install entr (fs watcher) on rhel by script
  script: install_entr.sh
  when: ansible_os_family != 'Debian'

- name: change dumpcap capabilities CAP_NET_RAW+eip => use wireshark as non-root
  capabilities: path="{{ dumpcap_path }}" capability='CAP_NET_RAW+eip'

- name: change dumpcap capabilities CAP_NET_ADMIN+eip => use wireshark as non-root
  capabilities: path="{{ dumpcap_path }}" capability='CAP_NET_ADMIN+eip'
