---
galaxy_info:
  author: Felix Archambault
  description: A role to install default packages on a machine used for daily developpement.
  license: MIT
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
      - 7
    - name: Fedora
      versions:
      - 21
      - 22
    - name: Ubuntu
      versions:
      - trusty
    - name: Debian
      versions:
      - wheezy
  galaxy_tags:
    - development
    - system

dependencies: []
