---

common_pkg_state: latest

selinux_state: disabled

# Default repos to configure on a target host.
RedHat_repodest: "/etc/yum.repos.d"
RedHat_repolist: []

Debian_repodest: '/etc/apt/sources.list.d'
Debian_repolist: []
