---
# defaults file for ansible-lxcm

private_dir: "{{ playbook_dir }}/private"

lxcm_default_grp: "{{ ansible_hostname }}_c"

# default container group to add container instance to
lxcm_child_grp:
  - "all_c"

# default dns domain (used when generating inventory dynamically)
lxcm_domain: "lxc"

# boolean to figure if we need to reprovision or not. Value dependends on
# lxcm_state.
lxcm_provision: false
