---
github_account: archf
# requirements: []

description: |
  This is a meta role to perform basic configuration. It contains no tasks and
  its sole purpose is to tie together the roles listed as dependencies below.

todos: []
role_stack: |
  This role was carefully selected to be part an ultimate deck of roles to manage
  your infrastructure.

  All roles' documentation is wrapped in this [convenient guide](http://127.0.0.1:8000/).
