---
galaxy_info:
  author: Felix Archambault
  description: A role to manage lxc containers on a host.
  license: MIT
  min_ansible_version: 2.0
  platforms:
  - name: Fedora
    versions:
    - 22
    - 23
  - name: Ubuntu
    versions:
    - trusty

  galaxy_tags:
    - system
    - containers

dependencies: []
