---
galaxy_info:
  author: Felix Archambault
  description: Ansible role to install packages on a host
  license: MIT
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
      - 7
    - name: Fedora
      versions:
      - 21
      - 22
    - name: Ubuntu
      versions:
      - trusty
    - name: Debian
      versions:
      - wheezy

  galaxy_tags:
    - system
    - packages

dependencies: []
