---
# tasks file for openssh-server

- name: load OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: sshd

- name: install openssh-server and openssh-client
  package: name={{ sshd_packages }} state=latest
  tags: sshd

- name: template sshd_config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
    backup: yes
    validate: '/usr/sbin/sshd -t -f %s'
  notify: restart_sshd
  tags: sshd
